### ISSUE TITLE
Some ideas from an author who is working on something similar to this project.

### ISSUE THREAD

**Issue by g-plane** [saadq/lynt#10]
Hi @saadq , I'm working on a project which is similar to this project: https://github.com/g-plane/methane . So let me tell you some ideas:
1. Use plugin-based architecture.
As we know, both ESLint and TSLint is so large with their dependencies. When installing ESLint and TSLint at the same time, it will cost much disk space. So if this project use plugin-based architecture will bring freedom to developers. BTW, plugin-based architecture doesn't mean it needs configuration. You can still keep zero-config with plugin-based architecture, just like how my project does.

2. Not everyone uses TypeScript and TSLint.
Most developers use pure JavaScript so they don't use TypeScript and TSLint. When a project haven't installed TypeScript, the package manager will warn that TypeScript is a peer dependency of TSLint. It's noisy.

---

And, as what I said above, [my project](https://github.com/g-plane/methane) is also a linter wrapper which is similar to this project `lynt`, so I can provide some help as I have some experience on this. For example, we could use a better linter formatter which is used in [my project](https://github.com/g-plane/methane):
- [eslint-formatter-beauty](https://github.com/g-plane/methane/tree/master/packages/eslint-formatter-beauty)
- [tslint-formatter-beauty](https://github.com/g-plane/methane/tree/master/packages/tslint-formatter-beauty)

Thanks.

**Comment by saadq** [comment]
I've been thinking on this for awhile. I'm a fan of your project, and I think its plugin architecture is pretty cool.

I'm struggling with the idea of doing this with `lynt` though. Though I am not satisfied with the size that `lynt` requires (even though it's just a devDependency), I think it is a tradeoff for convenience. The main goal of this project was to be easy and simple to use – it comes with everything, and you just tell it what stuff you want when you use it. I don't really want to make the user have to install multiple packages – that's one thing that annoyed me when I was a `standard` user and I had to always install `snazzy` alongside it.

I am also unhappy about the `peerDependency` warning, but I think a lot of `npm` users have tend to just tune it out from seeing it a lot.

I like your formatter – it's really nice. I'm just concerned about it possibly being too noisy it when you have multiple errors in multiple files. I like the current formatter for `lynt` as default, but I think having something like this might be cool as an alternate format with something like `lynt --verbose`.

**Comment by g-plane** [comment]
I agree with you.

**Comment by saadq** [comment]
Closing in favor of #17
