### ISSUE TITLE
Relax oppressive rules

### ISSUE THREAD

**Issue by saadq** [saadq/lynt#12]
Using this issue to keep a track of rules that should be removed because they are overly oppressive.

ESLint:

* `prefer-const`

TSLint:

* `prefer-const`
* `jsx-no-lambda`
* `only-arrow-functions`
* `jsx-no-multiline-js`
* `no-shadowed-variable`

**Comment by danielpa9708** [comment]
TSLint:
- `no-floating-promises` conflicting with mongoose projects

**Comment by saadq** [comment]
Fixed by #16
