### ISSUE TITLE
lynt removed all typecast type assertions 

### ISSUE THREAD

**Issue by whyboris** [saadq/lynt#14]
When I ran `npm run lynt --typescript --fix` _lynt_ removed type assertions from across the app.

For example:
```const abc: HTMLFormElement = <HTMLFormElement>nativeElement.querySelector('.xyz');```
became
```const abc: HTMLFormElement = nativeElement.querySelector('.xyz');```

I couldn't find any rule in my `tslint.json` that requested this change.

I suspect _some_ rule did this, but I couldn't find it in my _tslint.json_. Please comment if you know 🙇

**Comment by saadq** [comment]
Hmm, will look into this. But just to clarify – `lynt` does not use your `tslint.json`. It is basically a wrapper around TSLint and it uses its own config for it. The full TSLint config that is generated is here: https://github.com/saadq/lynt/blob/master/src/tslint/config.ts

If you'd rather use your own rules with your own config, you're probably better off just sticking with TSLint.

With that said, I'm going to take a look at these rules and see what could be causing this issue. Let me know if you find anything strange in there in the mean time!

**Comment by saadq** [comment]
Thinking it might be [this](https://github.com/palantir/tslint/issues/3540)

**Comment by whyboris** [comment]
Unrelated, but possibly a bug:
When trying to replicate the issue (because running the `lynt` command on the whole code base takes a while), I try to run `lynt` _just_ on a file that is changed, but it claims `No lynt errors`
command:
```lynt src/app/admin/edit-user/contact/contact.component.spec.ts --typescript --fix```

**Comment by whyboris** [comment]
I think you're correct about `'no-unnecessary-type-assertion'`
I removed the line `'no-unnecessary-type-assertion': true,` from `node_modules/lynt/lib/tslint/config.js` (manual hack) and re-ran the `npm run lynt` (pacagke.json command has --typescript --fix) and it no longer removed the type assertions!

**Comment by saadq** [comment]
`lynt` just uses TSLint's `--fix` flag, so I think the issue for that would need to be opened in the TSLint repo.

**Comment by saadq** [comment]
But let me know if for some reason this only happens when you run `lynt --fix` and not `tslint --fix`.

**Comment by saadq** [comment]
This rule has been removed entirely as of `v0.5.0`. Release notes: https://github.com/saadq/lynt/releases/tag/v0.5.0
