### ISSUE TITLE
Releases and/or Change log?

### ISSUE THREAD

**Issue by whyboris** [saadq/lynt#19]
Thank you for your work!
I just updated to the latest `0.3.1` from `0.2.0` and I'm sure I'm getting some goodies, but I have no idea what the changes are.

Perhaps you could add `CHANGELOG.md` or craft [Releases](https://github.com/saadq/lynt/releases) -- whatever is easiest, even if you just add a single sentence per release 🙇 🙇‍♀️

**Comment by saadq** [comment]
I think both sound like a good idea. The only reason I haven't currently been doing it was because I expected there to be a bunch of rule changes with the initial release, but it has slowed down a bit so I'll probably start doing this now. Thanks for the suggestion!

**Comment by saadq** [comment]
Created a release for `v0.4` manually here: https://github.com/saadq/lynt/releases/tag/v0.4.0

Will be using that `release` module for future releases, it looks great :D

Going to leave this open until I do the next release using that module.

**Comment by saadq** [comment]
On that note, because Lynt is technically not following semver until v1.0 is out (should be soon), I'm going to hold off on using that `release` package until then.

With that said, [v0.5.0](https://github.com/saadq/lynt/releases/tag/v0.5.0) is out, and every new update is getting release notes!
