### ISSUE TITLE
Tslint with exportedConfig and lynt  have different output

### ISSUE THREAD

**Issue by danielpa9708** [saadq/lynt#30]
Using tslint with the generated configuration with `--exportConfig` doesn't show all errors `lynt` shows

```
$ npx lynt --exportConfig

✔ tslint.json generated

$ npx lynt

/home/daniel/Documents/projects/ledd/scroll-utility/test/automate/index.ts
  43:15  Invalid 'await' of a non-Promise value.  await-promise

✖ 1 lynt error

$ npx tslint -p .
{ no output }
$ 
```

My lynt config in package.json:
```
  "lynt": {
    "typescript": true,
    "react": true,
    "rules": {
      "no-console": "on"
    }
  },
```

**Comment by saadq** [comment]
Weird, I'll look into it within ~2 days (Please feel free to ping me if I haven't said anything by then!). Thanks for reporting this.

**Comment by danielpa9708** [comment]
I looked up the code, and I think the problem is with the --project options, in tslint/index.ts if project is not specified it uses "." as default, but with the exportConfig this is not applied, then in the tslint/config it checks for the project property. Maybe I'll throw a PR when I have more time

**Comment by saadq** [comment]
v0.5.4 published with your fix, thanks a bunch!
