### ISSUE TITLE
Rule suggestion: no-var

### ISSUE THREAD

**Issue by albinekb** [saadq/lynt#8]
Referring to [this](http://eslint.org/docs/rules/no-var) rule 🔥

**Comment by saadq** [comment]
Now that rule configuration is possible, I feel a lot better about adding this by default, and if someone wants to support ES5 stuff, they can just do

```
{
  "rules": {
    "no-var": "off"
  }
}
```

in `.lyntrc` or `package.json`.

I'll probably add this in the next release.

**Comment by saadq** [comment]
This has been added to the config as of `v0.5.0`. Release notes: https://github.com/saadq/lynt/releases/tag/v0.5.0
