### ISSUE TITLE
Add a --format flag which uses Prettier

### ISSUE THREAD

**Issue by saadq** [saadq/lynt#9]
One of the main goals of `lynt` was to not include any style rules. To enforce consistent styling, the project highly recommends to use `prettier` alongside `lynt`. Because of this, it might be a good idea to include `prettier` as a dependency (or peerDependency) so that a user can just do something like:

```bash
$ lynt --format
```

Which will lint + run prettier on files. And doing this:

```bash
$ lynt --fix --format
```

will fix any lint errors and then format the output with Prettier. 

I'll wait for comments from other people before I try implementing this though.

**Comment by tomByrer** [comment]
But for those who don't use prettier, they'd have to install another unused package.  & more maintenance for you.  Keep in mind you'll have to add rules at least a few times a year as ECMAScript & TypeScript gets larger...

Is it hard for the masses to use prettier separately?

**Comment by saadq** [comment]
> Is it hard for the masses to use prettier separately?

I would say no. And when Prettier v2 will come out, it will be even easier. 

I guess my main motivation was that not allowing any style rules would mean people would install Prettier instead as a (better) replacement. If they were going to install Prettier anyways, it would be simpler to just include it as part of the package.

But I'm definitely hesitant about adding a large dependency like Prettier in, especially if it will go unused. I think when I made this issue, I may have been overeager. The whole point of `lynt` was to do one thing (linting for errors), and to do it well rather than focus on styling stuff. I think `lynt` should stick with doing that one thing well and not including random features unless it serves that purpose.
